# name: Schedule Reddit Scanner

# on:
#   schedule:
#     - cron: '0 11 * * *'  # 6 AM ET
#     - cron: '0 14 * * *'  # 9 AM ET
#     - cron: '0 17 * * *'  # 12 PM ET (noon)
#     - cron: '0 20 * * *'  # 3 PM ET
#     - cron: '0 23 * * *'  # 6 PM ET
#     - cron: '0 2 * * *'   # 9 PM ET
#     - cron: '0 5 * * *'   # 12 AM ET (midnight)

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.x'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install praw requests

#     - name: Run the script
#       run: |
#         python script.py
#       env:
#         CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
#         CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
#         USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
#         DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
